### ISSUE TITLE
Rearchitect Azure ML Extension for GA

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1110]
This epic will include all architecture changes which will be done as part of the GA. 

Refer to: [Azure Machine Learning Extension GA Plan.docx](https://microsoft.sharepoint.com/:w:/t/python/EW8jZAICQkVJrNBd8rGR45kBQYyxSj_2cuig4_5wymU37g?e=Rw7OtQ)

Entry Points Progress:
- [ ] azureml.cli.createResource	- Reimplement
- [ ] azureml.commandJob.createConfigFile	- Reimplement
- [ ] azureml.compute.createConfigFile	- Reimplement
- [ ] azureml.dataset.createConfigFile	- Reimplement
- [ ] azureml.datastore.createConfigFile	- Reimplement
- [ ] azureml.editor.cli.createResource	- Reimplement
- [ ] azureml.endpoint.createConfigFile	- Reimplement
- [ ] azureml.environment.createConfigFile	- Reimplement
- [ ] azureml.job.createConfigFile	- Reimplement
- [ ] azureml.model.createConfigFile	- Reimplement
- [ ] azureml.toolbar.job.createConfigFile	- Reimplement
- [ ] azureml.workspace.createConfigFile	- Reimplement
- [ ] azureml.yaml.createConfigFile	- Reimplement
- [ ] vscodeai.azureml.computeInstance.connectToJupyterServer	- Reimplement
- [ ] vscodeai.azureml.computeInstance.copyIpAddress	- Reimplement
- [ ] vscodeai.azureml.computeInstance.copySSHCommand	- Reimplement
- [ ] vscodeai.azureml.computeInstance.delete	- Reimplement
- [ ] vscodeai.azureml.computeInstance.remote.connect	- Reimplement
- [ ] vscodeai.azureml.computeInstance.remote.diagnosticReport	- Reimplement
- [ ] vscodeai.azureml.computeInstance.remote.killVSCodeServer	- Reimplement
- [ ] vscodeai.azureml.computeInstance.remote.killWebsocketServer	- Reimplement
- [ ] vscodeai.azureml.computeInstance.remote.uninstallVSCodeServer	- Reimplement
- [ ] vscodeai.azureml.computeInstance.restart	- Reimplement
- [ ] vscodeai.azureml.computeInstance.showSSHDocs	- Reimplement
- [ ] vscodeai.azureml.computeInstance.start	- Reimplement
- [ ] vscodeai.azureml.computeInstance.stop	- Reimplement
- [ ] vscodeai.azureml.computeInstance.viewProperties	- Reimplement
- [ ] vscodeai.azureml.computeTarget.detach	- Reimplement
- [ ] vscodeai.azureml.computeTarget.remove	- Reimplement
- [ ] vscodeai.azureml.computeTarget.viewProperties	- Reimplement
- [ ] vscodeai.azureml.dataset.definition.preview	- Reimplement
- [ ] vscodeai.azureml.dataset.definition.view	- Reimplement
- [ ] vscodeai.azureml.dataset.delete	- Reimplement
- [ ] vscodeai.azureml.dataset.mult.latest.preview	- Reimplement
- [ ] vscodeai.azureml.dataset.mult.latest.view	- Reimplement
- [ ] vscodeai.azureml.dataset.single.latest.preview	- Reimplement
- [ ] vscodeai.azureml.dataset.single.latest.view	- Reimplement
- [ ] vscodeai.azureml.datastore.delete	- Reimplement
- [ ] vscodeai.azureml.datastore.view	- Reimplement
- [ ] vscodeai.azureml.environment.view	- Reimplement
- [ ] vscodeai.azureml.experiment.hideArchived	- Reimplement
- [ ] vscodeai.azureml.experiment.preview	- Reimplement
- [ ] vscodeai.azureml.experiment.showArchived	- Reimplement
- [ ] vscodeai.azureml.model.download	Investigate/- Reimplement
- [ ] vscodeai.azureml.model.remove	- Reimplement
- [ ] vscodeai.azureml.model.viewProperties	- Reimplement
- [ ] vscodeai.azureml.remoteSSH.addNewSSHHost	- Reimplement
- [ ] vscodeai.azureml.remoteSSH.install	- Reimplement
- [ ] vscodeai.azureml.remoteSSH.openEmptyWindow	- Reimplement
- [ ] vscodeai.azureml.run.cancel	- Reimplement
- [ ] vscodeai.azureml.run.downloadLogs	- Reimplement
- [ ] vscodeai.azureml.run.downloadOutputs	- Reimplement
- [ ] vscodeai.azureml.run.log.download	- Reimplement
- [ ] vscodeai.azureml.run.log.view	- Reimplement
- [ ] vscodeai.azureml.run.output.download	- Reimplement
- [ ] vscodeai.azureml.run.preview	- Reimplement
- [ ] vscodeai.azureml.run.viewDetails	- Reimplement
- [ ] vscodeai.azureml.service.remove	- Reimplement
- [ ] vscodeai.azureml.service.viewProperties	- Reimplement
- [ ] vscodeai.azureml.toolbar.submit	- Reimplement
- [ ] vscodeai.azureml.workspace.changeDefault    - Reimplement
- [ ] vscodeai.azureml.workspace.filter	- Reimplement
- [ ] vscodeai.azureml.workspace.remove	- Reimplement
- [ ] vscodeai.azureml.workspace.setDefault	- Reimplement
- [ ] vscodeai.feedback.issue	- Reimplement
- [ ] vscodeai.feedback.proactive	- Reimplement
- [ ] vscodeai.selectSubscriptions	- Reimplement
- [ ] vscodeai.view.azureml.refresh	- Reimplement
- [ ] Compute Instance URI	- Reimplement
- [ ] Interactive session URI	- Reimplement

**Comment by shsuman** [comment]
- [] azureml.cli.createResource	Reimplement
 - [] azureml.commandJob.createConfigFile	Reimplement
 - [] azureml.compute.createConfigFile	Reimplement
 - [] azureml.dataset.createConfigFile	Reimplement
 - [] azureml.datastore.createConfigFile	Reimplement
 - [] azureml.editor.cli.createResource	Reimplement
 - [] azureml.endpoint.createConfigFile	Reimplement

**Comment by shsuman** [comment]
- [ ] azureml.cli.createResource	Reimplement
 - [ ] azureml.commandJob.createConfigFile	Reimplement
 - [ ] azureml.compute.createConfigFile	Reimplement
 - [ ] azureml.dataset.createConfigFile	Reimplement
 - [ ] azureml.datastore.createConfigFile	Reimplement
 - [ ] azureml.editor.cli.createResource	Reimplement
 - [ ] azureml.endpoint.createConfigFile	Reimplement

**Comment by shsuman** [comment]
Closing in favor of #1443
