### ISSUE TITLE
Gracefully handle CI new idle auto-shutdown scenarios for web and desktop 

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1707]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-tools-for-ai/issues/1992
- [ ] https://github.com/microsoft/vscode-tools-for-ai/issues/1993
- [ ] https://github.com/microsoft/vscode-tools-for-ai/issues/1994
```

---
## Goal
Azure ML customers are asking to see the notification that their compute will shutdown in ~30 min.
Also show a button to 'Skip this shutdown'  and update the schedule.

## Technical
- Notifications are websocket based 
- To edit the schedule use `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/computes/{computeName}/updateSchedules` and set its start time to now() + 1 day

## Questions
- Local and remote: Show for all compute instances in the default workspace?
- Remote: Show for the compute instance currently connected?
