### ISSUE TITLE
Enable Localization pipeline

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1897]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-tools-for-ai/issues/2004
- [ ] https://github.com/microsoft/vscode-tools-for-ai/issues/2005
- [ ] https://github.com/microsoft/vscode-tools-for-ai/issues/2006
```
