### ISSUE TITLE
Before connecting to remote compute instance need to reload the VS Code window and start over again

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#2036]
Users reported that every day they need to run the following flow to connect to compute instances:
1. User goes to ML Studio
2. Click on "VS Code" entry point from the compute instances list
3. VS Code open and the Azure ML extension shows a notification asking to "Reload" the window before continuing (related to the azure account issue)
4. User reloads the window and nothing happens (VS Code forgets about the URI that was started from Azure ML Studio)
5. User needs to either go back to ML Studio and start over or open the Azure ML extension tree view to connect with the context menu

```
[Debug - 2023-05-12 13:42:02.493] Registering Azure ML Uri Hanlder with path:  /computeInstance/remote

[Debug - 2023-05-12 13:42:02.494] Registering Azure ML Uri Hanlder with path:  /interactiveSession/distributedJob

[Debug - 2023-05-12 13:42:02.494] Registering Azure ML Uri Hanlder with path:  /interactiveSession

[Trace - 2023-05-12 13:42:02.496] DefaultWorkspace.showSelectWorkspacePromptIfNeeded called with arguments: [

    "No default Azure ML Workspace is selected. You need to select a default workspace to enable features such as completions and validations in your YAML files."

]

[Trace - 2023-05-12 13:42:02.497] DefaultWorkspaceService.get called with arguments: []

[Trace - 2023-05-12 13:42:02.567] Urihandler.handleUri called with arguments: [

    {

        "$mid": 1,

        "path": "/computeInstance/remote",

        "scheme": "vscode",

        "authority": "ms-toolsai.vscode-ai",

        "query": "computeId=%2Fsubscriptions%2F<REDACTED>%2FresourceGroups%2F<REDACTED>%2Fproviders%2FMicrosoft.MachineLearningServices%2Fworkspaces%2F<REDACTED>%2Fcomputes%2F<REDACTED>&sessionId=PaACR"

    }

]

[Debug - 2023-05-12 13:42:02.568] Uri scheme: vscode

[Debug - 2023-05-12 13:42:02.568] Uri authority: ms-toolsai.vscode-ai

[Debug - 2023-05-12 13:42:02.568] Uri path: /computeInstance/remote

[Trace - 2023-05-12 13:42:02.569] ComputeInstanceRemoteService.handleUri called with arguments: [

    {

        "telemetry": {

            "properties": {

                "isActivationEvent": "false",

                "lastStep": "",

                "result": "Succeeded",

                "stack": "",

                "error": "",

                "errorMessage": "",

                "telemetryTrackingId": "85135422-af62-4730-a559-67b5736fe8c2",

                "uriScheme": "vscode",

                "uriAuthority": "ms-toolsai.vscode-ai",

                "uriPath": "computeInstance-remote"

            },

            "measurements": {

                "duration": 0

            },

            "suppressIfSuccessful": false,

            "suppressAll": false

        },

        "errorHandling": {

            "suppressDisplay": false,

            "rethrow": false,

            "issueProperties": {}

        },

        "ui": {

            "_onDidFinishPromptEmitter": {

                "j": false

            },

            "_isPrompting": false,

            "_context": "[Circular]"

        },

        "valuesToMask": [],

        "callbackId": "UriHandler.handleUri"

    },

    {

        "$mid": 1,

        "path": "/computeInstance/remote",

        "scheme": "vscode",

        "authority": "ms-toolsai.vscode-ai",

        "query": "computeId=%2Fsubscriptions%2F<REDACTED>%2FresourceGroups%2F<REDACTED>%2Fproviders%2FMicrosoft.MachineLearningServices%2Fworkspaces%2F<REDACTED>%2Fcomputes%2F<REDACTED>&sessionId=PaACR"

    }

]

[Debug - 2023-05-12 13:42:02.570] Ensuring Azure Machine Learning - Remote extension is installed

[Debug - 2023-05-12 13:42:02.571] Azure Machine Learning - Remote extension is already installed

[Debug - 2023-05-12 13:42:02.571] Attempting to activate the extension: Azure Machine Learning - Remote

[Trace - 2023-05-12 13:42:03.059] AuthenticationService.promptLoginIfNecessary called with arguments: []

[Trace - 2023-05-12 13:42:03.062] Telemetry Event: authentication/needsLogin Measures: undefined Props: {

    "result": "false"

}

[Debug - 2023-05-12 13:42:03.062] Compute id is passed. Fetching the compute instance from SDK

[Trace - 2023-05-12 13:42:03.062] AuthenticationService.getAzureMLService called with arguments: [

    "<REDACTED>"

]

[Trace - 2023-05-12 13:42:03.062] AuthenticationService.getSubscriptionById called with arguments: [

    "<REDACTED>"

]

[Trace - 2023-05-12 13:42:03.062] AuthenticationService.listSubscriptions called with arguments: []

[Trace - 2023-05-12 13:42:03.064] Telemetry Event: authentication/needsLogin Measures: undefined Props: {

    "result": "false"

}

[Debug - 2023-05-12 13:42:03.549] Prompting the user for feedback.

[Error - 2023-05-12 13:42:03.553] Error: Your VS Code window must be reloaded to perform this action.

[Trace - 2023-05-12 13:42:03.565] DefaultWorkspaceService.clear called with arguments: []

[Trace - 2023-05-12 13:42:03.566] Refreshing tree view

[Trace - 2023-05-12 13:42:03.566] DefaultWorkspaceService.get called with arguments: []

[Trace - 2023-05-12 13:42:03.566] AuthenticationService.listVisibleSubscriptions called with arguments: []

[Trace - 2023-05-12 13:42:03.571] Telemetry Event: authentication/needsLogin Measures: undefined Props: {

    "result": "true"

}

[Debug - 2023-05-12 13:42:03.571] User needs to login to Azure Account

[Trace - 2023-05-12 13:42:03.585] Refreshing tree view

[Trace - 2023-05-12 13:42:03.586] DefaultWorkspaceService.get called with arguments: []
```

## Tasks
- [ ] Telemetry analysis of the issue (users impacted, how often it happens, how often the reload is required)
- [x] Tag this issue in upstream azure account issue
- [ ] Design a workaround and estimate the required work

**Comment by sevillal** [comment]
- [ ] Telemetry analysis of the issue (users impacted, how often it happens, how often the reload is required)
- [ ] Tag this issue in upstream azure account issue
- [ ] Design a workaround and estimate the required work

**Comment by sevillal** [comment]
Caused by: https://github.com/microsoft/vscode-azure-account/issues/53

**Comment by sevillal** [comment]
Thanks @wmeints for letting us know, we'll keep you posted on the progress we make to fix this.

**Comment by sevillal** [comment]
Closing in favor of https://github.com/microsoft/vscode-tools-for-ai/issues/2094
