### ISSUE TITLE
[Dashboard] Create dashboard page for desktop reliability rate

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#2156]
```[tasklist]
### Tasks
- [x] Create baseline reliability rate tile
- [x] Create top errors table tile
- [x] Create baseline tile showing number of connection starts
- [x] Create reliability rate by extension version tile
- [x] Add count to table of version reliability
- [x] Filter reliability to last 5 versions
- [x] Errors over time tile
- [x] Add error categories and filter out host/user/data errors from reliability rate
- [x] Create reliability rate over time tile
```
