### ISSUE TITLE
Consolidating remote extensions

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#2389]
### Plan and technical design
- [x] #2300

### Phase 0
- [x] #2390
- [x] Bug bash
#### Rollout
  - [x] #2394
  - [x] #2403
  - [x] #2404
  - [x] Publish Stable version of the extension default to use the refactored consolidation code
  - [x] Monitor reliability metrics of the Stable version and deliver fixes to improv any impact until we reach the baseline reliability
  - [ ] Remove legacy/unused code 
    - [x] #2391

### Phase 1
- [x] #2398
- [x] #2428
- [x] https://github.com/microsoft/vscode-dev/issues/1190
- [ ] Wait for authentication fix to be in vscode.dev stable (tentative first week of September)
- [ ] Move a small percentage of customers to use the new URL (vscode.dev/+ms-tools-ai.vscode-ai-remote)
- [ ] Monitor reliability metrics of the experiment

### Phase 2
- [ ] Move 100% of customers to use the new URL
- [ ] Monitor reliability metrics

### Phase 3
- [ ] PM work
- [ ]
