### ISSUE TITLE
Datastores: User can create, view, inspect, edit and unregister datastores in their workspace

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#255]

**Comment by sevillal** [comment]
**Tasks**

- [ ] Top level "Data Stores" node
    - [ ] Need icon
    - [ ] Order in where to put the icon in relation to the other top level nodes
- [ ] Show automatically created data stores "workspaceblobstore", "workspacefilestore"
- [ ] Show child nodes under "Data Stores" top level
    - [ ] AzureBlob need icon (or could we use the one from Azure Storage extension)
    - [ ] AzureDataLake need icon
    - [ ] AzureDataLakeGen2 need icon
    - [ ] AzureFile need icon (or could we use the one from Azure Storage extension)
    - [ ] AzurePostgreSql need icon
    - [ ] AzureSqlDatabase need icon
    - [ ] DBFS need icon
    - [ ] GluterFs need icon
- [ ] Command to set "Default" datastore
    - [ ] Is this allowed for any type of datastore?
- [ ] Show node label on "Default" datastore
