### ISSUE TITLE
Datastores: User can create datastores

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#452]
**Tasks**

- [x] Context menu "Create Data Store" under "Data Stores" top level to start datastore creation
- [x] Palette command "AzureML: Create Data Store" to start data store creation
- [x] Input datastore name
- [x] Selector for type: "Blob Container", "File Share"
- [x] Input storage account or default to the account associated with the workspace
- [x] Choose existing "blob container" or "file share"
- [x] Show final JSON with information about the datastore
